name: Check Docs

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck for documentation
        run: |
          staticcheck -checks=exported ./...