name: Publish documentation

on:
  pull_request:
    branches: [ "main" ]  
  push:
    branches: [ "main" ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Generate documentation with godox
        run: |
          go install github.com/rohit-px/godox@latest
          mkdir -p docs-html
          godox -path=. -output=docs-html -title="golang-toolkit"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-html